# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_url', models.URLField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('short_code', models.URLField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bookmark')),
            ],
            options={
                'ordering': ['-access_time'],
            },
        ),
    ]
