# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='short_code',
            field=models.CharField(max_length=30),
        ),
    ]
