# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160301_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={},
        ),
        migrations.RemoveField(
            model_name='click',
            name='access_time',
        ),
        migrations.AddField(
            model_name='click',
            name='clicked',
            field=models.BooleanField(default=True),
        ),
    ]
